tag

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,12 +25,21 @@ jobs:
         id: get_version
         run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
 
+      - name: Check if Version Exists
+        id: check_version
+        run: |
+          if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
+            echo "A tag v${{ steps.get_version.outputs.version }} already exists."
+            echo "Version already exists. Failing the job."
+            exit 1
+          fi
+
       - name: Build Application
         shell: bash
         run: |
-            ls
-            npm install
-            npm run build
+          ls
+          npm install
+          npm run build
 
       - name: Commit Changes to Main Branch
         run: |
@@ -42,7 +51,7 @@ jobs:
           git commit -m "Update dist folder for version ${{ steps.get_version.outputs.version }}"
           git tag -a "${{ steps.get_version.outputs.version }}" -m "Version ${{ steps.get_version.outputs.version }}"
           git push origin v${{ steps.get_version.outputs.version }} --tags
-        
+
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
@@ -53,11 +62,10 @@ jobs:
           release_name: Release ${{ steps.get_version.outputs.version }}
           draft: false
           prerelease: false
-        
+
       - name: Merge to Main
         run: |
-            git fetch origin main
-            git checkout main
-            git merge v${{ steps.get_version.outputs.version }} --no-ff -m "Merge pre-release v${{ steps.get_version.outputs.version }} into main"
-            git push origin main
-  
+          git fetch origin main
+          git checkout main
+          git merge v${{ steps.get_version.outputs.version }} --no-ff -m "Merge pre-release v${{ steps.get_version.outputs.version }} into main"
+          git push origin main
